=== tetrazon/epam-courses/task08/src/main/resources/data/orangery.xsd
<?xml version="1.1" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.training.by/task08/flowers"
        xmlns:tns="http://www.training.by/task08/flowers"
        elementFormDefault="qualified">
    <element name="flowers">
        <complexType>
            <sequence>
                <element name="flower" type="tns:Flower"
                         minOccurs="2"
                         maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>
    <element name="visualParams" type="tns:VisualParams"/>
    <element name="growingTips" type="tns:GrowingTips"/>

    <complexType name="VisualParams">
        <sequence>
            <element name="stColor" type="string"/>
            <element name="lfColor" type="string"/>
            <element name="avSize" type="positiveInteger"/>
        </sequence>
    </complexType>

    <complexType name="GrowingTips">
        <sequence>
            <element name="temperature" type="double"/>
            <element name="light" type="boolean"/>
            <element name="water" type="double"/>
        </sequence>
    </complexType>

    <complexType name="Flower">
        <sequence>
            <element name="name" type="string"/>
            <element name="soil">
                <simpleType>
                    <restriction base="string">
                        <enumeration value="podzolic"/>
                        <enumeration value="ground"/>
                        <enumeration value="sod-podzolic"/>
                    </restriction>
                </simpleType>
            </element>
            <element name="origin" type="string"/>
            <element name="visualParams" type="tns:VisualParams"/>
            <element name="growingTips" type="tns:GrowingTips"/>
            <element name="multiplying">
                <simpleType>
                <restriction base="string">
                    <enumeration value="leaf"/>
                    <enumeration value="stalk"/>
                    <enumeration value="seed"/>
                </restriction>
                </simpleType>
            </element>
            <element name="growDate" type="date"/>
        </sequence>
        <attribute name="itemName" type="tns:ItemName" use="required"/>
        <attribute name="isPoisoning" type="boolean" default="false"/>
    </complexType>

    <simpleType name="ItemName">
        <restriction base="ID">
            <pattern value="[a-zA-Z]{2,19}\-[a-z0-9]{3}"/>
        </restriction>
    </simpleType>



</schema>

=== tetrazon/epam-courses/task08/out/artifacts/task08xmlxsdwebparsing_war_exploded/WEB-INF/classes/data/orangery.xml
<?xml version ="1.0" encoding = "UTF-8"?>
<flowers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://www.training.by/task08/flowers"
         xsi:schemaLocation="http://www.training.by/task08/flowers  orangery.xsd">
    <flower itemName="agava-001" isPoisoning="false">
        <name>Agava</name>
        <soil>podzolic</soil>
        <origin>Mexico</origin>
        <visualParams>
            <stColor>green</stColor>
            <lfColor>green</lfColor>
            <avSize>1</avSize>
        </visualParams>
        <growingTips>
            <temperature>25</temperature>
            <light>true</light>
            <water>200</water>
        </growingTips>
        <multiplying>leaf</multiplying>
        <growDate>2020-11-11</growDate>
    </flower>
    <flower itemName="aloe-002" >
        <name>Aloe</name>
        <soil>ground</soil>
        <origin>South Africa</origin>
        <visualParams>
            <stColor>green</stColor>
            <lfColor>green</lfColor>
            <avSize>2</avSize>
        </visualParams>
        <growingTips>
            <temperature>25</temperature>
            <light>true</light>
            <water>250</water>
        </growingTips>
        <multiplying>stalk</multiplying>
        <growDate>2020-11-11</growDate>
    </flower>
    <flower itemName="ananas-001">
        <name>Ananas</name>
        <soil>sod-podzolic</soil>
        <origin>Argentina</origin>
        <visualParams>
            <stColor>yellow</stColor>
            <lfColor>green</lfColor>
            <avSize>2</avSize>
        </visualParams>
        <growingTips>
            <temperature>25</temperature>
            <light>true</light>
            <water>300</water>
        </growingTips>
        <multiplying>leaf</multiplying>
        <growDate>2020-10-10</growDate>
    </flower>
    <flower itemName="begonia-001">
        <name>Begonia</name>
        <soil>podzolic</soil>
        <origin>Central Africa</origin>
        <visualParams>
            <stColor>dark green</stColor>
            <lfColor>green</lfColor>
            <avSize>1</avSize>
        </visualParams>
        <growingTips>
            <temperature>25</temperature>
            <light>true</light>
            <water>150</water>
        </growingTips>
        <multiplying>stalk</multiplying>
        <growDate>2019-10-10</growDate>
    </flower>
    <flower itemName="haemanthus-001">
        <name>Haemanthus</name>
        <soil>sod-podzolic</soil>
        <origin>South Africa</origin>
        <visualParams>
            <stColor>light green</stColor>
            <lfColor>light green</lfColor>
            <avSize>1</avSize>
        </visualParams>
        <growingTips>
            <temperature>25</temperature>
            <light>true</light>
            <water>300</water>
        </growingTips>
        <multiplying>stalk</multiplying>
        <growDate>2019-10-10</growDate>
    </flower>
    <flower itemName="hibiscus-001">
        <name>Hibiscus</name>
        <soil>ground</soil>
        <origin>East Asia</origin>
        <visualParams>
            <stColor>red</stColor>
            <lfColor>green</lfColor>
            <avSize>1</avSize>
        </visualParams>
        <growingTips>
            <temperature>25</temperature>
            <light>false</light>
            <water>300</water>
        </growingTips>
        <multiplying>stalk</multiplying>
        <growDate>2019-05-10</growDate>
    </flower>
    <flower itemName="eupatorium-001">
        <name>Eupatorium</name>
        <soil>podzolic</soil>
        <origin>Mexico</origin>
        <visualParams>
            <stColor>light green</stColor>
            <lfColor>green</lfColor>
            <avSize>2</avSize>
        </visualParams>
        <growingTips>
            <temperature>20</temperature>
            <light>false</light>
            <water>350</water>
        </growingTips>
        <multiplying>stalk</multiplying>
        <growDate>2019-10-15</growDate>
    </flower>
    <flower itemName="jasminum-001">
        <name>Jasminum</name>
        <soil>sod-podzolic</soil>
        <origin>India</origin>
        <visualParams>
            <stColor>brown</stColor>
            <lfColor>white</lfColor>
            <avSize>2</avSize>
        </visualParams>
        <growingTips>
            <temperature>20</temperature>
            <light>false</light>
            <water>350</water>
        </growingTips>
        <multiplying>stalk</multiplying>
        <growDate>2019-01-10</growDate>
    </flower>
    <flower itemName="zantedeschia-001">
        <name>Zantedeschia</name>
        <soil>podzolic</soil>
        <origin>South Africa</origin>
        <visualParams>
            <stColor>dark green</stColor>
            <lfColor>white</lfColor>
            <avSize>1</avSize>
        </visualParams>
        <growingTips>
            <temperature>25</temperature>
            <light>false</light>
            <water>150</water>
        </growingTips>
        <multiplying>stalk</multiplying>
        <growDate>2019-10-05</growDate>
    </flower>
    <flower itemName="cardamomum-001">
        <name>Cardamomum</name>
        <soil>ground</soil>
        <origin>India</origin>
        <visualParams>
            <stColor>dark green</stColor>
            <lfColor>light green</lfColor>
            <avSize>3</avSize>
        </visualParams>
        <growingTips>
            <temperature>20</temperature>
            <light>false</light>
            <water>600</water>
        </growingTips>
        <multiplying>stalk</multiplying>
        <growDate>2014-10-10</growDate>
    </flower>
    <flower itemName="cordyline-001">
        <name>Cordyline</name>
        <soil>podzolic</soil>
        <origin>Malasya</origin>
        <visualParams>
            <stColor>dark green</stColor>
            <lfColor>violet</lfColor>
            <avSize>1</avSize>
        </visualParams>
        <growingTips>
            <temperature>20</temperature>
            <light>false</light>
            <water>150</water>
        </growingTips>
        <multiplying>stalk</multiplying>
        <growDate>2019-03-10</growDate>
    </flower>
    <flower itemName="laurus-001">
        <name>Laurus</name>
        <soil>ground</soil>
        <origin>Mediterranean</origin>
        <visualParams>
            <stColor>brown</stColor>
            <lfColor>light green</lfColor>
            <avSize>3</avSize>
        </visualParams>
        <growingTips>
            <temperature>20</temperature>
            <light>false</light>
            <water>600</water>
        </growingTips>
        <multiplying>stalk</multiplying>
        <growDate>2019-10-10</growDate>
    </flower>
    <flower itemName="citrus-001">
        <name>Citrus</name>
        <soil>ground</soil>
        <origin>Asia</origin>
        <visualParams>
            <stColor>light green</stColor>
            <lfColor>yellow</lfColor>
            <avSize>2</avSize>
        </visualParams>
        <growingTips>
            <temperature>25</temperature>
            <light>false</light>
            <water>600</water>
        </growingTips>
        <multiplying>seed</multiplying>
        <growDate>2019-10-10</growDate>
    </flower>
    <flower itemName="lutic-001" isPoisoning="true">
        <name>Lutic</name>
        <soil>ground</soil>
        <origin>Europe</origin>
        <visualParams>
            <stColor>light green</stColor>
            <lfColor>yellow</lfColor>
            <avSize>1</avSize>
        </visualParams>
        <growingTips>
            <temperature>15</temperature>
            <light>false</light>
            <water>50</water>
        </growingTips>
        <multiplying>stalk</multiplying>
        <growDate>2019-10-10</growDate>
    </flower>
</flowers>
